### ISSUE TITLE
undefined symbol: _ZN2cv11imreadmulti

### ISSUE THREAD

**Issue by kempffer** [tractatus/wholebrain#14]
** testing if installed package can be loaded
Error: package or namespace load failed for ‘wholebrain’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/wholebrain/libs/wholebrain.so':
  /usr/local/lib/R/site-library/wholebrain/libs/wholebrain.so: undefined symbol: _ZN2cv11imreadmultiERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERSt6vectorINS_3MatESaIS9_EEi
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/wholebrain’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/tmp/RtmpKwz7AJ/file4334d9e74bc/wholebrain_0.1.1.tar.gz’ had non-zero exit status

its impossible to install wholebrain on ubuntu 18, and windows 7.
also its not possible to get wholebrain working in a new user account on a win7 pc where wholebrain already installed and working......

**Comment by tractatus** [comment]
Hi @kempffer you do not provide sufficient information in your issue request. What is the OpenCV version?

The error:

`_ZN2cv11imreadmultiERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERSt6vectorINS_3MatESaIS9_EE`

Indicates an error with your openCV version and not wholebrain.

**Comment by kempffer** [comment]
i think 4.1 but i dont know
ive tryed so much versions and so much combinations....
the actually combinations is the best one

maybe you should install virtualbox, install a plain version of windows and/or linux and try to install it by yourself
and you will seee that the installation as described on the website will not work.

or simply offer a virtual machine image which have a linux AND wholebrain installed

**Comment by tractatus** [comment]
@kempffer please change your tone. It is not constructive dialog. You need to state what you did and what linking issues you have. If you have multiple versions and linking on your system that will create issues.

**Comment by tractatus** [comment]
@kempffer you can begin with reporting:
`pkgbuild::find_rtools(debug = TRUE)
`as well as:
`devtools::session_info()`
Since your issue indicates that you are running a compiler with cant fintthe C++11 standard library installed on your system (as indicated by `cxx1112basic_stringIcSt11char_traits`). That would most likely point to your Rtools and not OpenCV.

**Comment by unetzjuser** [comment]
I just encountered the same problem (on Ubuntu 18.04 x64). Will try your suggestions@tractatus

I have successfully installed wholebrain on my Mac and it works well. This is a very nice tool. Thank you very much!

**Comment by unetzjuser** [comment]
I have three additional problems with installation:

**No.1**
getContour.cpp: In function ‘SEXPREC* getContour(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)’:
getContour.cpp:191:103: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘std::vector<std::vector<cv::Point_<int> > >::size_type {aka long unsigned int}’ [-Wformat=]
       printf("Largest contour: %d, # contours detected: %d \n", largest_contour_index, contours.size());
                                                                                        ~~~~~~~~~~~~~~~^
getContour.cpp:210:48: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘std::vector<std::vector<cv::Point_<int> > >::size_type {aka long unsigned int}’ [-Wformat=]
     printf("LOOP DONE: %d \n", contours.size() );
                                ~~~~~~~~~~~~~~~ ^
**No.2**
webfiles.cpp: In function ‘SEXPREC* createWeb(SEXP, SEXP, SEXP, SEXP, SEXP)’:
webfiles.cpp:200:19: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
             system(tilegrouppath.c_str());
             ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~

**No.3**
Warning in data(connectivity, envir = environment()) :
  data set ‘connectivity’ not found

I am not sure how these will affect the library eventually... Anyway I will start troubleshooting from checking Rtools first.

**Comment by unetzjuser** [comment]
Well, I just did some troubleshooting. Progress updated:

1. Rtools is for Windows OS. I am using Linux, so trying the codes below does not help:
pkgbuild::find_rtools(debug = TRUE)
devtools::session_info()

2. I downloaded the package as a .zip file and tried to install wholebrain from local source. The same errors occurred.
So I manipulated the getContour.cpp and webfiles.cpp files:
1) Editing the content a bit (some people say "use namespace std" is not good, so I tried a few codes). Fail.
2) Removing these files from the .zip file, then of course error No.1 and 2 as I posted earlier would not happen. But still, error No.3 appeared. Then load failure is not due to the two .cpp files.

3. I load the connectivity.Rdata and tried to install again. Fail.

Considering these, could you please help me to see the problem and proceed? 

Many thanks! 

> @kempffer you can begin with reporting:
> `pkgbuild::find_rtools(debug = TRUE) `as well as:
> `devtools::session_info()`
> Since your issue indicates that you are running a compiler that cant find the C++11 standard library installed on your system (as indicated by `cxx1112basic_stringIcSt11char_traits`). That would most likely point to your Rtools and not OpenCV.

**Comment by tractatus** [comment]
@unetzjuser all points you raise are simply compiler warnings and not errors these will not affect anything. If you are unaware that Rtools is a set of compiler tools for Windows then I think randomly digging around in the source code base don warnings will do little. You error is related to the compiler and libstdc++ you currently have installed on your linux distro.

I suggest you try the linux docker instead:
https://github.com/crazyhottommy/wholebrain_docker

**Comment by unetzjuser** [comment]
This is an easy solution. I have pulled the image and now have no problems.

Thank you very much!!

> @unetzjuser all points you raise are simply compiler warnings and not errors these will not affect anything. If you are unaware that Rtools is a set of compiler tools for Windows then I think randomly digging around in the source code based on warnings will do little. Your error is related to the compiler and libstdc++ you currently have installed on your linux distro.
> 
> I suggest you try the linux docker instead:
> https://github.com/crazyhottommy/wholebrain_docker
