### ISSUE TITLE
Installation Problem Linux/Ubuntu 

### ISSUE THREAD

**Issue by Sattlert2** [tractatus/wholebrain#15]
Hello, I am having a problem installing wholebrain in Ubuntu. When running the line "devtools::install_github("tractatus/wholebrain")" I keep receiving an error in the terminal window "Error in ROpenCVLite::opencvConfig("cflags") : OpenCV is not installed on this system. Please use installOpenCV() to install it. Execution halted". I have opencv version 3.2.0. I am unsure if it is because I installed it differently then your installation guide says. I followed this: "https://stackoverflow.com/questions/45582565/opencv-cmake-error-no-such-file-or-directory-on-ubuntu" by user Kallz. I installed the package in R as well. Thank you for your help.

**Comment by Sattlert2** [comment]
Has anyone had experience with this issue?

**Comment by tractatus** [comment]
Hi @Sattlert2 you dont have to install OpenCV yourself infact wholebrain will look for 
ROpenCVLite to install it for you.

It should have done so when installing wholebrain but most likely you got an error message from ROpenCVLite that something in the installation procedure did not work.

So just use:
`ROpenCVLite::installOpenCV() `
To see if R can install OpenCV for you and see if there are any error messages when doing that before running devtools::install_github() of wholebrain.

**Comment by Sattlert2** [comment]
Thank you so much! I am not really experienced with many software. This worked.
