### ISSUE TITLE
get.image command not working

### ISSUE THREAD

**Issue by epilepneuro** [tractatus/wholebrain#23]
Hello,

When trying to batch process, the output of this code is incorrect. My folder has 47 tiff images.

```
animal<-'C:/Users/R/Desktop/PVcompressed'
> images<-get.images(animal)
> length(images)
[1] 1

```
Could you please let me know what to fix?

Thanks.

**Comment by tractatus** [comment]
`animal<-'C:/Users/R/Desktop/PVcompressed/'
 images<-get.images(animal, type = 'tiff')
 length(images)`

**Comment by epilepneuro** [comment]
thank you!
