### ISSUE TITLE
Error in createfilter(filename) : could not find function "createfilter"

### ISSUE THREAD

**Issue by arashnh11** [tractatus/wholebrain#27]
Hi Daniel,

First of all, thanks for sharing your great work and for being responsive to the issues. I am working on a containerized version of your code to run it on a high-performance computing cluster and I almost got there. In fact, I could get the screenshot below at some point. But later on, R couldn't find the "createfilter" function library from the Namespace? Could you please have a look? 

![Screen Shot 2019-12-19 at 4 36 12 PM](https://user-images.githubusercontent.com/18223861/71230762-ea647380-22b8-11ea-8318-d6831f790d55.png)

> library(wholebrain) 
Loading required package: Rcpp
Loading required package: png
Loading required package: MASS
Loading required package: grImport
Loading required package: grid
Loading required package: XML
Loading required package: sp
Loading required package: rgl
Loading required package: misc3d
Loading required package: plyr
WholeBrain (version 0.1.35) "Thurstone" 
 by Daniel Fürth, 2018, by using this software you agree to the EULA
> filename<-system.file('sample_tiles/rabiesEGFP.tif', package='wholebrain') 
> filter<-createfilter(filename) 
Error in createfilter(filename) : could not find function "createfilter"

**Comment by arashnh11** [comment]
Maybe should I explicitly point to those library function definitions? If so how can I get the path?

**Comment by tractatus** [comment]
@arashnh11 Dont think I ever included a createfilter function. I can see it is on my to do list. Probably my idea was for people to have a quick qay to initialize such an object.

A filter is just a list object with something like this:
```
myfilter<-list(alim = c(40, 999),
threshold.range = c(0, 1463),
eccentricity = 360L,
Max = 1500, Min = 0,
brain.threshold = 30,
resize = 0.03,
blur = 3,
downsample = 0.25)
```

**Comment by arashnh11** [comment]
Oh, shoot...
I was testing with the Archlinux verification that had that function call instead of the ubuntu/Debian one which indeed had a different function call with segment. 
This is resolved. 
library(wholebrain) 
filename<-system.file('sample_tiles/rabiesEGFP.tif', package='wholebrain') 
seg<-segment(filename)

**Comment by arashnh11** [comment]
Also, 
I am working with our researchers to verify this container. Once stable, I would be happy to share that with you and I am sure that would make a lot of researchers who are struggling to install this on their Linux systems. 

The solution is a singularity/docker container from ubuntu 14.04 that is running on CentOS 7.6 
Any operating system that has singularity installed should be able to execute the container.

**Comment by tractatus** [comment]
@arashnh11 sounds good. Let me know how it goes.
