### ISSUE TITLE
Trouble Installing Linux - GNU Linker typo

### ISSUE THREAD

**Issue by clarkdc** [tractatus/wholebrain#28]
Hello,

I wanted to report an issue installing wholebrain on CentOS 7. When running:

>  devtools::install_github("tractatus/wholebrain") 

every library builds except 'wholebrain.so':

g++ -std=gnu++11 -shared -L/share/pkg.7/r/3.6.0/install/lib64/R/lib -L/usr/local/lib64 -o wholebrain.so CThinPlateSpline.o CoherentPointShift.o DoubleSlider.o ThinPlateSpline.o Widget.o affine.o connectedcomponents3D.o display.o filter.o flatfieldcorrection.o gauss_transform.o gauss_transform_make_default.o getContour.o imageconverter.o laplacianpyramidblending.o lwtimagetest.o makeAtlasNissl.o manualsegmentation.o matrix.o multiresolutiondecomposition.o nonrigid.o normalization.o rigid.o transform.o utils.o wavelet2d.o webfiles.o -L/usr/local/lib/ -lfftw3 -lm -llapack -Wl,-rpath=/usr3/bustaff/clarkdc/R/x86_64-pc-linux-gnu-library/3.6/opencv/lib -L/usr3/bustaff/clarkdc/R/x86_64-pc-linux-gnu-library/3.6/opencv/lib -l -L/share/pkg.7/r/3.6.0/install/lib64/R/lib -lR
/usr/bin/ld: cannot find -l-L/share/pkg.7/r/3.6.0/install/lib64/R/lib

There seems to be a missing input to the last '-l' linker flag. Pasting this command to the terminal without the empty '-l' builds the 'wholebrain.so' properly but loading wholebrain with library(wholebrain) with every library built results in the error ''wholebrain' is not a valid installed pacakge'.

-Dustin

**Comment by tractatus** [comment]
@clarkdc this error is strange:
`/usr/bin/ld: cannot find -l-L/share/pkg.7/r/3.6.0/install/lib64/R/lib`
Looks like `-l` flag before `-L` flag.

**Comment by tractatus** [comment]
@clarkdc check that OpenCVLite was properly installed. Looks like it could be the thing that wasnt installed based on the opencv linking.

`ROpenCVLite::opencvVersion()`

Report from R what that says.

**Comment by clarkdc** [comment]
Thank you for your quick response Daniel. Yes, this is an awkward error as there should be a path argument to the ‘-l’ but as the next text is ‘-L/share/pkg.7/r/3.6.0/install/lib64/R/lib’ it seems to take that second ‘-L’ linking as the argument to ‘-l’ which is of course invalid.

You are correct that ROpenCVLite::opencvVersion() is not working properly despite loading the library without error (there seems to be a discrepancy in the name of the library directory between the installation and this function). Also, we are using gcc 4.8.5 on CentOS7 which might be an issue if you are recommending 4.9.3. We have had success with wholebrain locally on Linux Mint and Windows so this installation on our cluster is not high priority for us but I’d be happy to keep you updated with my progress if I find a way to configure it properly. However, please don’t exert any extra effort on our part as we are happy with the local installations and it is likely an issue with our own environment.

Thank you again,

Dustin

**Comment by tractatus** [comment]
@clarkdc most likely I think it is ROpenCVLite missing. On *nix systems the linking flags are set by:
https://github.com/tractatus/wholebrain/blob/master/src/Makevars

If ROpenCVLite would be returning a space or something like that I could imagine that being sent as the weird command.

ROpenCVLite will take care of OpenCV for you so might be good to have anyway.
You can install it from CRAN and then let it compile OpenCV:
`install.packages("ROpenCVLite")
ROpenCVLite::installOpenCV()`
