### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by max-poltora** [tractatus/wholebrain#30]
I have a problem while installing ROpenCVLite on my Windows. I execute the following command and receive the error message:
> devtools::install_github("swarm-lab/ROpenCVLite")
Skipping install of 'ROpenCVLite' from a github remote, the SHA1 (783a2f04) has not changed since last install.
  Use `force = TRUE` to force installation
> devtools::install_github("swarm-lab/ROpenCVLite", force=TRUE)
Downloading GitHub repo swarm-lab/ROpenCVLite@master
   checking for file 'C:\Users\user\AppData\Local\Temp\Rtmpym4vYp\remotes23b8441c724d\swarm-lab-ROpenCVLite-783a2f0/DESCRIPTION' ...
   checking for file 'C:\Users\user\AppData\Local\Temp\Rtmpym4vYp\remotes23b8441c724d\swarm-lab-ROpenCVLite-783a2f0/DESCRIPTION' ... 
√  checking for file 'C:\Users\user\AppData\Local\Temp\Rtmpym4vYp\remotes23b8441c724d\swarm-lab-ROpenCVLite-783a2f0/DESCRIPTION'
-  preparing 'ROpenCVLite': (377ms)
   checking DESCRIPTION meta-information ...
   checking DESCRIPTION meta-information ... 
√  checking DESCRIPTION meta-information
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Removed empty directory 'ROpenCVLite/man/figures'
-  building 'ROpenCVLite_4.30.1.tar.gz'
Warning:
   Warning: file 'ROpenCVLite/configure' did not have execute permissions: corrected
Installing package into ‘C:/Users/user/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'ROpenCVLite' ...
Error in system("sh ./configure.win") : 
  (converted from warning) 'sh' not found
* removing 'C:/Users/user/Documents/R/win-library/3.5/ROpenCVLite'
* restoring previous 'C:/Users/user/Documents/R/win-library/3.5/ROpenCVLite'
In R CMD INSTALL
Error: Failed to install 'ROpenCVLite' from GitHub:
  (converted from warning) installation of package ‘C:/Users/user/AppData/Local/Temp/Rtmpym4vYp/file23b832224d3c/ROpenCVLite_4.30.1.tar.gz’ had non-zero exit status

Can you please help me understand this issue?

**Comment by tractatus** [comment]
This is not related to wholebrain but rather ROpenCVlite and the error has been solved and documented before, please check:

https://github.com/rwinlib/rtools35/issues/11
