### ISSUE TITLE
opencv was built in newer version than linked

### ISSUE THREAD

**Issue by jorareshuaiwang** [tractatus/wholebrain#38]
Hi everyone and Daniel @tractatus, I am having a trouble when installing wholebrain, the error seems from opencv which is built for macOS 10.15 but was linked to macOS 10.13. I installed opencv using ROpenCVLite::installOpenCV(). 

The errors showed during installing wholebrain: 
/bin/sh: pkg-config: command not found
ld: warning: dylib (/Library/Frameworks/R.framework/Versions/4.0/Resources/library/opencv/lib/libopencv_calib3d.dylib) was built for newer macOS version (10.15) than being linked (10.13)

Thanks so much!
Best,
Shuai

**Comment by JoyOtten** [comment]
Hi Jora!,

I also performed it in this way today. In my case it works perfectly to first install OpenCV with ROpenCVLite::installOpenCV(). After that I installed the wholebrain package. I also got a warning namely was built for newer macOS version (11.0) than being linked (10.13). However, it was still able to install the wholebrain package.

**Comment by jorareshuaiwang** [comment]
Hi Joy,

Thanks for your reply! Yes I later realized the installation worked, although the package always aborts in R studio, but works fine in R console.

Thanks again.
