### ISSUE TITLE
Issue with wholebrain installation due to registration export fail in the namespace

### ISSUE THREAD

**Issue by mjin1812** [tractatus/wholebrain#41]
Here is my error in the console.

![image](https://user-images.githubusercontent.com/42684103/125642317-bf1c2f54-b3bf-43ab-b559-ed82f75ec85b.png)

**Comment by mjin1812** [comment]
I suspect this has to do with the recent merge of the pull request regarding 'fixing transformationgrid$mx[index] out of bounds error', where the function registration() is renamed registration_MLA()

**Comment by tractatus** [comment]
Hi @mjin1812 thanks for being so quick to spot this!
I should have never merged that pull request without running unit tests.
I changed the name of the function back. So should work now.
Currently on vacation so cant test. Will try to set up travis on this repo for the future because of this.

**Comment by tractatus** [comment]
@mjin1812 compiles fine now. Will run unit tests when Im back at keyboard.

**Comment by mjin1812** [comment]
Thanks for the quick response on this!

**Comment by tractatus** [comment]
Great will close this now
