### ISSUE TITLE
An error occurs during installation with R console.

### ISSUE THREAD

**Issue by MasahiroMorsihita** [tractatus/wholebrain#45]
I really appreciate your efforts to make wholebrain as open-source. 
I followed your tutorial to install on Mac but I get the following error and WholeBrain from R does not complete.
I hope the issue is resolved and can use the software.　Thank you.

I am running in the following environment.
MacBook Pro (13-inch, M1, 2020)
macOS 11,6
R R version 4.1.1 (2021-08-10) -- "Kick Things" Platform: aarch64-apple-darwin20 (64-bit)
Xcode 12.5.1 (12E507)
XQuartz 2.8.1 (xorg-server 1.20.11)
OpenCV 3.2
fftw 3.3.9_1

The status when the code is entered into the R Commander according to the installation instructions is as follows.
> if (!require(devtools)) {
+   install.packages("devtools")
+ }
Loading required package: devtools
Loading required package: usethis
> devtools::install_github("tractatus/wholebrain")
Downloading GitHub repo tractatus/wholebrain@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                       
2: CRAN packages only        
3: None                      
4: xfun (0.25 -> 0.26) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 3
✔  checking for file ‘/private/var/folders/yw/5mbb8y0j5flb5rhr6jfrzt400000gn/T/Rtmp9X885m/remotes74965b363691/tractatus-wholebrain-1cc9634/DESCRIPTION’ ...
─  cleaning srcCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  looking to see if a ‘data/datalist’ file should be addedd shell scripts
─  building ‘wholebrain_0.1.1.tar.gz’ (1.9s)
   building ‘wholebrain_0.1.1.tar.gz’ (1.9s)
clang++ -arch arm64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG `pkg-config --cflags fftw3` `Rscript -e 'ROpenCVLite::opencvConfig("cflags")'` -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include  `Rscript -e 'Rcpp:::CxxFlags()'` -I../inst/include "-std=c++11" -fPIC  -falign-functions=64 -Wall -g -O2  -c CThinPlateSpline.cpp -o CThinPlateSpline.o
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/yw/5mbb8y0j5flb5rhr6jfrzt400000gn/T//Rtmp9X885m/file7496794df4de/wholebrain_0.1.1.tar.gz’ had non-zero exit status
> 
> library(wholebrain)
Error in library(wholebrain) : there is no package called ‘wholebrain’
> filename<-system.file('sample_tiles/rabiesEGFP.tif', package='wholebrain')
> output<-segment(filename) 
Error in segment(filename) : could not find function "segment"
>

**Comment by tractatus** [comment]
It doesnt look like you have the compiler with Xcode installed and working properly.

Its hard to tell on my end what exactly you did when trying to install since you don't provide anymore information.

But I would assume that you either don't have Xcode installed properly or way more likely you installed it but you failed to activate the command line tools of Xcode. 

If you have Xcode installed from the terminal enter
```
xcode-select -p
```

and press return to install the command line tools portion of Xcode.

**Comment by MasahiroMorsihita** [comment]
Thank you for your advice.
However, I tried reinstalling xcode and command line tool, but the result was the same.
I don't know the cause, but it seems that wholebrain is difficult to install for me. I am very unfortunate.

**Comment by tractatus** [comment]
You are not showing the full error message when you are trying to compile the package so it is hard for me to help you further in this regard. There has to be an Error message displayed and it is most likely related to either your compiler set up or that a dependent package is not installed properly.
You are going to have problems installing R packages broadly in this regard and it is not specific to WholeBrain.

try download the wholebrain repository as a zip file and unzip and open the Rproject file in Rstudio and Build and compile from the Build tab up in the top right panel in Rstudio. That will also display any OS issues that devtools might suppress for you.

**Comment by tractatus** [comment]
Also verify that the command line tools are installed through terminal by:
```
xcode-select --install
```

**Comment by MasahiroMorsihita** [comment]
Thank you so much! The problem seemed to be that I was using R for m1 Mac and OpenCV was not installed properly.
I installed it from R (for intel CPU and using rosetta) instead of from Homebrew and the problem was solved. Now that I've got it up and running, I'd like to try it out while watching the tutorial video. I am very happy that I can use it.
