### ISSUE TITLE
Brain image flipped when saving registration

### ISSUE THREAD

**Issue by kohlkopf** [tractatus/wholebrain#7]
Upon viewing registration with `inspect.registration()` everything is in order, the atlas matches with the brain image and the active neurons seems to labeled correctly. When saving this with `dev.copy()`, the brain image becomes flipped. Everything else remains in order.

`inspect.registration(regi, seg)`
![image](https://user-images.githubusercontent.com/28633777/49885964-2b03f400-fdfe-11e8-9edd-01bc9c58a8b3.png)

`dev.copy(pdf, paste0("~/Desktop/registrations/", tools::file_path_sans_ext(basename(images[i])), '.pdf'))` *look closely for the flipped brain image*
![image](https://user-images.githubusercontent.com/28633777/49885954-26d7d680-fdfe-11e8-92d1-9c7f5e00a57b.png)

**Comment by tractatus** [comment]
This is not a bug and is not related to WholeBrain as such but has to do with how different OSes use graphical devices.

The dev.copy() is different than a normal device there is a batch.mode flag inside inspect.registration that should be used just for this purpose. batch.mode = FALSE is default so set it to batch.mode = TRUE if you are running batch mode inside a loop and saving to file with dev.copy() without plotting to a device. If the background raster image is upside down will be different form different OSes but the flag TRUE or FALSE will change this either way.

This is covered in the tutorial on running batches of images:
[Process multiple sections with a pipeline.](http://www.wholebrainsoftware.org/cms/tutorials/#pipeline)

See this part:
```
dev.copy(pdf, paste0(tools::file_path_sans_ext(basename(images[i])), '.pdf'))
dataset<-inspect.registration(regi, seg, soma = TRUE, forward.warps = TRUE, batch.mode = TRUE)
dev.off()
```

If your images are still upside down with this command then change the batch.mode flag back to FALSE.

**Comment by kohlkopf** [comment]
That did solve it, I'd forgotten to change the default. On MacOS changing to `batch.mode=TRUE` worked. Thanks!
